# Generated by Django 5.0.6 on 2024-06-09 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Population',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(max_length=100)),
                ('year', models.PositiveSmallIntegerField()),
                ('human_count', models.PositiveBigIntegerField()),
            ],
        ),
    ]
